apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: poker-aa

resources:
  - namespace.yaml
  - redis.yaml
  - mysql.yaml
  # - kafka.yaml
  - game-server.yaml
  - nginx-configmap.yaml
  - nginx.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: poker-aa
  app.kubernetes.io/managed-by: kustomize
